#! /bin/sh

APPLICATION_NAME=consul
APPLICATION_PORT=8500
APPLICATION_HOME=$(dirname "$0")
APPLICATION_CMD=
APPLICATION_JAVA_OPTS=

if [ "$CONSUL_HOMEx" != "x" ]; then
    APPLICATION_HOME=$CONSUL_HOME
fi

if [ "$1x" != "x" ]; then
    APPLICATION_PORT=$1
fi

if [ "$JAVA_OPTSx" != "x" ]; then
    APPLICATION_JAVA_OPTS=$JAVA_OPTS
fi

echo "Running docker $APPLICATION_NAME$1..."
echo "APPLICATION_PORT=$APPLICATION_PORT"
echo "APPLICATION_HOME=$APPLICATION_HOME"

docker kill $APPLICATION_NAME$1
docker rm $APPLICATION_NAME$1

docker run -d \
    -e JAVA_OPTS="$APPLICATION_JAVA_OPTS" \
    -e APP_PROFILE="$APPLICATION_PROFILE" \
    -v $APPLICATION_HOME/data:/consul/data \
    -p $APPLICATION_PORT:8500 \
    --name $APPLICATION_NAME$1 $APPLICATION_NAME $APPLICATION_CMD

